### ISSUE TITLE
feature request: pivot tables?

### ISSUE THREAD

**Issue by cchance27** [jmcnamara/rust_xlsxwriter#53]
### Feature Request

Any chance that you plan to add the ability to do pivot tables on a range of cells?

**Comment by jmcnamara** [comment]
I've had a look at this in the past (a couple of times) and unfortunately it is too large and complicated to tackle. Some of the issues are:

- The internal plumbing is quite large and replicates a lot of the data for the target dataset in a number of files. That isn't a deal breaker but Excel does a lot of magic in the UI that hides a lot of complexity in the background.
- The API would be large (again not really a deal breaker and could be done over time but if you look at the UI in Excel and think about how it could be mapped to a code API you will get a sense of the scale)
- The main deal breaker is that Excel file format doesn't automatically generate the pivot so it would need to be provided by the user or calculated by the library. Neither of which is trivial. The filtered/pivoted rows also need to be hidden manually/programmatically.  That requires replicating the logic of the pivot in the code. (I implemented something similar for autofilters but it would be much harder for pivots).
- Also, since it hasn't already been implemented in the Python library I don't have the test suite that helps accelerate and validate the new Rust code.

So overall this is a can't/won't fix (more can't than won't since Pivots are a killer feature for Excel).

**Comment by grovesNL** [comment]
@jmcnamara I have a small prototype that uses `saveData` of 0 and `refreshOnLoad` of 1 to skip including the records into the pivot cache. I think this avoids some of the problems you mentioned. e.g., we shouldn't have to evaluate filters.

This approach seems to work fine for simple use cases, like providing a pre-configured pivot table with the data source referencing another sheet and fields for row/column/values. Would there be any interest in supporting something like that?

**Comment by jmcnamara** [comment]
> I have a small prototype that uses `saveData` of 0 and `refreshOnLoad` of 1 to skip including the records into the pivot cache. I think this avoids some of the problems you mentioned. e.g., we shouldn't have to evaluate filters.

@grovesNL That is a clever idea. Are you able to create files without a cache in Excel or are you doing it programmatically?

**Comment by grovesNL** [comment]
I'm doing it programmatically with a local branch of `rust_xlsxwriter` that writes pivot tables. Excel has options to disable writing pivot cache records and control how refreshing works.

<img width="377" height="201" alt="Image" src="https://github.com/user-attachments/assets/dfffb432-7965-4d1f-b178-53f9127d2e5a" />

The pivot cache technically includes all of the column definitions so you still need those. You can use something like this for the pivot cache definitions:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pivotCacheDefinition xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" saveData="0" refreshOnLoad="1" refreshedBy="rust_xlsxwriter" refreshedDate="0" createdVersion="6" refreshedVersion="6" minRefreshableVersion="3" recordCount="8">
    <cacheSource type="worksheet">
        <worksheetSource ref="A1:D9" sheet="Data"/>
    </cacheSource>
    <cacheFields count="4">
        <cacheField name="Region" numFmtId="0">
            <sharedItems/>
        </cacheField>
        <cacheField name="Product" numFmtId="0">
            <sharedItems/>
        </cacheField>
        <cacheField name="Sales" numFmtId="0">
            <sharedItems/>
        </cacheField>
        <cacheField name="Quantity" numFmtId="0">
            <sharedItems/>
        </cacheField>
    </cacheFields>
</pivotCacheDefinition>
```
and the pivot table itself:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pivotTableDefinition xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" name="SalesByRegion" cacheId="1" applyNumberFormats="0" applyBorderFormats="0" applyFontFormats="0" applyPatternFormats="0" applyAlignmentFormats="0" applyWidthHeightFormats="1" dataCaption="Values" updatedVersion="6" minRefreshableVersion="3" useAutoFormatting="1" itemPrintTitles="1" createdVersion="6" indent="0" outline="1" outlineData="1" multipleFieldFilters="0">
    <location ref="A3:B4" firstHeaderRow="1" firstDataRow="2" firstDataCol="1"/>
    <pivotFields count="4">
        <pivotField axis="axisRow" showAll="0">
            <items count="1">
                <item t="default"/>
            </items>
        </pivotField>
        <pivotField showAll="0"/>
        <pivotField dataField="1" showAll="0"/>
        <pivotField showAll="0"/>
    </pivotFields>
    <rowFields count="1">
        <field x="0"/>
    </rowFields>
    <rowItems count="1">
        <i t="grand">
            <x/>
        </i>
    </rowItems>
    <dataFields count="1">
        <dataField name="Sum of Sales" fld="2"/>
    </dataFields>
    <pivotTableStyleInfo name="PivotStyleLight16" showRowHeaders="1" showColHeaders="1" showRowStripes="0" showColStripes="0" showLastColumn="0"/>
</pivotTableDefinition>
```

(some of these tags can probably be cleaned up further, this is just what I quickly hacked together)

**Comment by jmcnamara** [comment]
> Excel has options to disable writing pivot cache records and control how refreshing works.

Ok. Good to know. I'll play around with that and try to figure out if is a suitable approach for a general API.

**Comment by grovesNL** [comment]
Ok great. For what it's worth, in my prototype the API looks something like this:

```rust
let pivot_table = PivotTable::new()
    .set_name("SalesByYear")
    .set_data_source("Data!$A$1:$D$9")
    .set_style(PivotTableStyle::Medium9)
    .set_show_column_grand_total(true)
    .set_show_row_grand_total(true)
    .add_filter_field("Year")
    .add_row_field("Region")
    .add_column_field("Product")
    .add_data_field(PivotTableDataField::new("Sales").set_function(PivotTableFunction::Sum));

pivot_worksheet.add_pivot_table(0, 0, &pivot_table)?;
```

which results in

<img width="824" height="544" alt="Image" src="https://github.com/user-attachments/assets/3e98515d-e4f4-4b66-96ab-b42becc7a99d" />

`set_data_source` uses a generic for the cell range (similar to `set_categories`).

**Comment by jmcnamara** [comment]
@grovesNL Could you attach a couple of example xlsx files based on  the data in the `populate_autofilter_data()` function in the `./examples/app_autofilter.rs` file.

Also, what are you using as the range in `<location ref="A3:B4" ...`

**Comment by grovesNL** [comment]
Sure, here are a couple examples.

The first example creates a filtered pivot table using `populate_autofilter_data()`:

- Generated programmatically using my branch [pivot_table_filter.xlsx](https://github.com/user-attachments/files/24642707/pivot_table_filter.xlsx)
- After opening pivot_table_filter.xlsx in Excel and saving [pivot_table_filter_saved.xlsx](https://github.com/user-attachments/files/24642706/pivot_table_filter_saved.xlsx)

<img width="871" height="394" alt="Image" src="https://github.com/user-attachments/assets/35fea599-dbf1-4bf5-9b14-a930bddad3fc" />

The next example writes multiple pivot tables:

- Generated programmatically using my branch [pivot_table_multiple.xlsx](https://github.com/user-attachments/files/24642705/pivot_table_multiple.xlsx)
- After opening pivot_table_multiple.xlsx in Excel and saving [pivot_table_multiple_saved.xlsx](https://github.com/user-attachments/files/24642708/pivot_table_multiple_saved.xlsx)

<img width="603" height="393" alt="Image" src="https://github.com/user-attachments/assets/c723484e-c343-42ec-888a-c0b9545d6655" />

<img width="1310" height="402" alt="Image" src="https://github.com/user-attachments/assets/f833cc14-58f2-4e7c-82ca-c0fe59190aff" />

> Also, what are you using as the range in <location ref="A3:B4" ...

Excel always appears to use the first cell (top left) of the range), so a single cell like `<location ref="A2"` should work. Excel will expand it out automatically when it refreshes the pivot table.

For the pivot_table_multiple.xlsx example it's easy enough to place the pivot tables so they overlap as they're being refreshed/expanded. Excel won't refresh them in this case because it will provide an error about the tables overlapping. The file still opens fine though.

**Comment by jmcnamara** [comment]
@grovesNL Thanks. I finally got a chance to look at the files you provided and I think this is probably a reasonable workaround for most people. It is also implementable so I'm going to put it on the near-term backlog.

Thanks for the suggestion.

**Comment by SGmuwa** [comment]
Hello all. I needed pivot tables for my own project, so I implemented them myself.
Here is the diff: https://github.com/jmcnamara/rust_xlsxwriter/compare/main...SGmuwa:rust_xlsxwriter:issues/53

It follows the `saveData="0"` + `refreshOnLoad="1"` workaround suggested by @grovesNL, plus a number format, layout and data field name on top of it.

I have not opened a pull request, for two reasons. First, the changes were written entirely by Opus 5, not by me. Second, I did not look at any other version of the library, the Python one included, while implementing this.

I also did not attach any screenshots for the doc examples: I only have Google Drive and LibreOffice here, no Excel, so the images would not match the ones in the rest of the documentation.

If you would still like to take these changes, I can open a pull request, or you are welcome to pull the branch yourself.

**Comment by radelqui** [comment]
LibreOffice Calc doesn't have a built-in pivot table feature like Excel's, but you can get pretty close using Data Pilot (in older versions) or the current "Pivot Table" tool, which honestly does exist but is easy to miss.

Here's how: 1. Select your data range including headers. 2. Go to Insert > Pivot Table. 3. In the dialog, choose "Current selection" and hit OK. 4. You'll get a layout dialog. Drag your field names into the Row Fields, Column Fields, and Data Fields areas, just like you would in Excel. 5. Click OK and it generates the pivot table on a new sheet.

A few tips: right-click any cell in the resulting pivot table to refresh it after changing source data. You can also double-click a data cell to drill down into the records behind that number. If you need to change the summary function (say from SUM to COUNT), drag the field into the Data area again and pick the function you want.

It's not as polished as Excel's version, but it handles most common pivot scenarios fine, grouping by dates, multiple data fields, filters, etc.

What if every time you hit a wall like this, you had someone right inside your document who could walk you through it or just do it for you on the spot? That's basically what ME Office AI does. Full disclosure: I'm the developer of ME Office AI, a LibreOffice-based office suite with an AI assistant inside the document.
https://apps.microsoft.com/detail/9PCV4RCJCFXV?cid=gh-meoffice

**Comment by jmcnamara** [comment]
Just to note. This is still my preferred #1 priority for a new feature in `rust_xlsxwriter` and Python `XlsxWriter`. However, I have been having difficulties carving out the time to tackle it due to maintenance work on `calamine` and also just a shortage of time. I will get to it though.
