### ISSUE TITLE
Bug: header_format and table_default are incompatible

### ISSUE THREAD

**Issue by claudiofsr** [jmcnamara/rust_xlsxwriter#90]
### Current behavior

I use rust_xlsxwriter in [find-identical-files](https://github.com/claudiofsr/find-identical-files).

If 

I comment out line 98 of the [excel.rs](https://github.com/claudiofsr/find-identical-files/blob/master/src/excel.rs) file [.set_row_format(0, fmt_header)?]

and

I uncomment line 17 of the [path_info.rs](https://github.com/claudiofsr/find-identical-files/blob/master/src/structures/path_info.rs) file [header_format = get_xlsx_format("header")],

the header format is changed.

To verify:
```
cd /tmp
git clone https://github.com/claudiofsr/find-identical-files.git
cd find-identical-files
cargo run -- -tx .
```
See the XLSX file "fif.xlsx" with and without the changes.

### Expected behavior

```
#[derive(XlsxSerialize, Serialize)]
#[xlsx(
    header_format = get_xlsx_format("header"),
    table_default
)]
pub struct PathInfo {
...
}
```

I hope 

the header_format and table_default options are compatible
and
`.set_row_format(0, fmt_header)?` is not necessary.

**Comment by jmcnamara** [comment]
I ran the example with and without the changes and got the following:

Without changes.

![screenshot](https://github.com/jmcnamara/rust_xlsxwriter/assets/94267/f9197dad-ae34-4c5a-b1f7-fd4eed080a35)

With changes:

![screenshot](https://github.com/jmcnamara/rust_xlsxwriter/assets/94267/55a9fb90-6d1f-4c50-b648-059d8ed722cf)

I see that one version has some alignment properties and the other doesn't.

That is probably correct in terms of what is specified in the code. The row format and the table header format are separate. In `rust_xlsxwriter` and Excel. The `rust_xlsxwriter` library doesn't attempt to apply the row format to the table header because of this separation. (It does however apply the format to cells outside the table.)

In this particular case I think you should be setting the table header and not the row format but it is hard to tell from the description alone.

**Comment by claudiofsr** [comment]
You could implement the set_header_format(some_format) method in Worksheet and differentiate .set_row_format(row_num, some_format) from .set_header_format(some_format) [use excluded for header].

set_header_format would be fully compatible with

#[xlsx(
header_format = some_format,
table_default
)].

I don't know if this makes sense to you.

**Comment by jmcnamara** [comment]
> I don't know if this makes sense to you.

Not really. I'm still not sure what the issue is. Do you think you could break this down into a small runnable example that demonstrates the issue.

**Comment by claudiofsr** [comment]
Instead of just one PathInfo structure, there would be PathInfo1 and PathInfo2, and PathInfo1 would have the format FFF1 and PathInfo2 would have the format FFF2.

Using

```
    worksheet
        .set_name(sheet_name)?
        .set_row_height(0, 32)?
        .set_row_format(0, fmt_header)? // <---
        .set_freeze_panes(1, 0)?;
```
would not be the solution!

**Comment by jmcnamara** [comment]
Sorry. I still don’t understand what the issue is. Try explain with a reproducible example.
